"""empty message

Revision ID: 69cd406e6332
Revises: ddbf56822f2b
Create Date: 2020-03-31 23:29:07.161243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cd406e6332'
down_revision = 'ddbf56822f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolist', ['list_id'], ['id'])
    op.execute('INSERT INTO todolist (name) VALUES (\'uncategorized\');')
    op.execute('UPDATE todos SET list_id=1 where list_id is null;')
    op.alter_column('todos', 'list_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolist')
    # ### end Alembic commands ###
