"""empty message

Revision ID: ddbf56822f2b
Revises: 1394b62d98ec
Create Date: 2020-03-30 23:00:37.971616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbf56822f2b'
down_revision = '1394b62d98ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # FABIO -  handle existing data
    op.execute('UPDATE todos SET completed=False where completed is null;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
